openapi: 3.0.0
info:
  title: Contacts Store API
  description: API for managing contacts
  version: 1.0.0
servers:
  - url: https://contacts-store.onrender.com
paths:
  /contacts:
    get:
      summary: Retrieve all contacts
      responses:
        '200':
          description: A list of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
    post:
      summary: Add a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
  /contacts/{id}:
    put:
      summary: Update a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - in: body
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
